### ISSUE TITLE
Only supports prime on amazon.com

### ISSUE THREAD

**Issue by TCBroad** [jonluca/Perfect-Prime#1]
I use UK prime and the url is https://www.amazon.co.uk/gp/video/...

**Comment by jonluca** [comment]
Thanks for the report. I'll update it to support all TLDs later tonight. Thanks!

**Comment by jonluca** [comment]
Apologies for the delay. I have uploaded version `0.0.3` which should support all country TLDs. Thanks for bringing this to my attention!
